// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using CogTourist.Core;

namespace CogTourist
{
	public partial class LandmarkViewController : UIViewController
	{
		public LandmarkViewController (IntPtr handle) : base (handle)
		{
            
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            photoButton.TouchUpInside += (sender, e) =>
            {
                var alert = UIAlertController.Create("Vision", "Pick or take photos", UIAlertControllerStyle.ActionSheet);

                var photoAction = UIAlertAction.Create("Pick photo", UIAlertActionStyle.Default, async (obj) =>
                {
					var ls = new LandmarkService();

					var identity = await ls.PickPhotoForIdentification();

					var img = new UIImage(NSData.FromStream(identity.Photo));

					selectedPhoto.Image = img;

					descriptionLabel.Text = identity.Description;
                });

                alert.AddAction(photoAction);

                var cameraAction = UIAlertAction.Create("Take photo", UIAlertActionStyle.Default, async (obj) =>
                {
					var ls = new LandmarkService();

					var identity = await ls.TakePhotoForIdentification();

					var img = new UIImage(NSData.FromStream(identity.Photo));

					selectedPhoto.Image = img;

					descriptionLabel.Text = identity.Description;
                });
                alert.AddAction(cameraAction);

                PresentViewController(alert, true, null);
            };
        }
                           
	}
}
